# This file is part of Adblock Plus <https://adblockplus.org/>,
# Copyright (C) 2006-present eyeo GmbH
#
# Adblock Plus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# Adblock Plus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Adblock Plus.  If not, see <http://www.gnu.org/licenses/>.

spec:
  inputs:
    workspacepath:
      type: string
      description: "Path to the workspace directory"
      default: "."
    parent_pipeline_source:
      type: string
      description: "Value of CI_PIPELINE_SOURCE in the parent pipeline"

---
default:
  image: node:18.17.1
  cache:  # Cache modules using lock file
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  tags:
    - "GCP"
  interruptible: true

stages:
  - build
  - checkfilesizes
  - unit
  - compliance
  - uitests

# Pipeline rules
.always:
  rules:
    # Do not trigger merge request pipelines
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: always

.release-or-main:
  rules:
    # Do not trigger merge request pipelines
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    # Run automatically on release and main branch
    - if: $CI_COMMIT_BRANCH == "adblockplus-release" || $CI_COMMIT_BRANCH == "main"
    # Run manually on all other branches
    - when: manual
      allow_failure: true

################################################################################
# Build
################################################################################

.build:
  stage: build
  before_script:
    # Update dependencies
    - npm ci --cache .npm --prefer-offline

lint:
  extends: .build
  script:
    - npm run -w $[[ inputs.workspacepath ]] lint

build:
  extends: .build
  script:
    # Create .env file from CI variables
    - echo "CDP_AGGREGATE_URL=\"$ADBLOCKPLUS_CDP_AGGREGATE_URL\"" >> $[[ inputs.workspacepath ]]/.env
    - echo "CDP_BEARER=\"$ADBLOCKPLUS_CDP_BEARER\"" >> $[[ inputs.workspacepath ]]/.env
    - echo "CDP_PING_URL=\"$ADBLOCKPLUS_CDP_PING_URL\"" >> $[[ inputs.workspacepath ]]/.env
    - echo "EYEOMETRY_BEARER=\"$ADBLOCKPLUS_EYEOMETRY_BEARER\"" >> $[[ inputs.workspacepath ]]/.env
    - echo "EYEOMETRY_URL=\"$ADBLOCKPLUS_EYEOMETRY_URL\"" >> $[[ inputs.workspacepath ]]/.env
    - echo "SENTRY_DSN=\"$ADBLOCKPLUS_SENTRY_DSN\"" >> $[[ inputs.workspacepath ]]/.env
    - echo "SENTRY_ENVIRONMENT=\"$ADBLOCKPLUS_SENTRY_ENVIRONMENT\"" >> $[[ inputs.workspacepath ]]/.env
    # Create source archive
    - npm run -w $[[ inputs.workspacepath ]] build:source
    # Create extension builds
    - npm run -w $[[ inputs.workspacepath ]] build:release
  artifacts:
    name: "adblockplus-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - $[[ inputs.workspacepath ]]/dist/release/adblockplus-*.tar.gz
      - $[[ inputs.workspacepath ]]/dist/release/adblockplus-chrome-*-mv2.zip
      - $[[ inputs.workspacepath ]]/dist/release/adblockplus-chrome-*-mv3.zip
      - $[[ inputs.workspacepath ]]/dist/release/adblockplus-chromedevelopment-*-mv3.zip
      - $[[ inputs.workspacepath ]]/dist/release/adblockplus-firefox-*-mv2.xpi

buildfromsource:
  stage: build
  needs: ["build"]
  before_script:
    - cd $[[ inputs.workspacepath ]]
  script:
    # We need to generate the builds outside of the git repo to avoid any
    # implicit dependencies to git in our build scripts
    - mkdir /tmp/source
    - tar xvf dist/release/adblockplus-*.tar.gz -C /tmp/source
    - cd /tmp/source
    - npm ci --cache .npm --prefer-offline
    # Create extension builds from source archive
    - npm run -w $[[ inputs.workspacepath ]] build:release
  after_script:
    # We cannot refer to artifacts in directories outside of the project
    - cp -r /tmp/source/$[[ inputs.workspacepath ]]/dist/release $[[ inputs.workspacepath ]]/dist/source
  artifacts:
    name: "adblockplus-source-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - $[[ inputs.workspacepath ]]/dist/source/adblockplus-chrome-*-mv2.zip
      - $[[ inputs.workspacepath ]]/dist/source/adblockplus-chrome-*-mv3.zip
      - $[[ inputs.workspacepath ]]/dist/source/adblockplus-firefox-*-mv2.xpi
  rules:
    - !reference [.release-or-main, rules]

# ################################################################################
# # Check filesizes
# ################################################################################

.checkfilesizes:
  image: alpine:latest
  stage: checkfilesizes
  before_script:
    - cd $[[ inputs.workspacepath ]]
  script:
   - unzip -d unpacked-extension/ dist/release/$EXTENSION
   - cd unpacked-extension/
   - if [ $(find . -type f -name '*.js' -size +4000k | wc -l) -gt 0 ]; then
       echo 'Some extension files are bigger than 4 MB:' &&
       find . -type f -name '*.js' -size +4000k -exec ls -lh {} \; &&
       exit 1;
     else
       echo 'All extension files are smaller than 4 MB' &&
       exit 0;
     fi

checkfilesizes:MV3:chrome:
  extends: .checkfilesizes
  variables:
    EXTENSION: adblockplus-chrome-*-mv3.zip

checkfilesizes:MV2:chrome:
  extends: .checkfilesizes
  variables:
    EXTENSION: adblockplus-chrome-*-mv2.zip

checkfilesizes:MV2:firefox:
  extends: .checkfilesizes
  variables:
    EXTENSION: adblockplus-firefox-*-mv2.xpi

# ################################################################################
# Check build sizes
# ################################################################################

.checkbuildsizes:
  stage: checkfilesizes
  before_script:
    - cd $[[ inputs.workspacepath ]]
    - if [ ! -f $SOURCE_BUILD ] || [ ! -f $REPOSITORY_BUILD ]; then
        echo "File not found" &&
        exit 1;
      fi
  script:
    - if((`stat -c%s $REPOSITORY_BUILD`!=`stat -c%s $SOURCE_BUILD`)); then
        echo "Build from source archive and build from the repository are not the same size" &&
        ls -l $REPOSITORY_BUILD &&
        ls -l $SOURCE_BUILD &&
        exit 1;
      else
        echo "Build from source archive and build from the repository are the same size" &&
        exit 0;
      fi
  rules:
    - !reference [.release-or-main, rules]

checkbuildsizes:MV3:chrome:
  extends: .checkbuildsizes
  variables:
    REPOSITORY_BUILD: dist/release/adblockplus-chrome-*-mv3.zip
    SOURCE_BUILD: dist/source/adblockplus-chrome-*-mv3.zip

checkbuildsizes:MV2:chrome:
  extends: .checkbuildsizes
  variables:
    REPOSITORY_BUILD: dist/release/adblockplus-chrome-*-mv2.zip
    SOURCE_BUILD: dist/source/adblockplus-chrome-*-mv2.zip

checkbuildsizes:MV2:firefox:
  extends: .checkbuildsizes
  variables:
    REPOSITORY_BUILD: dist/release/adblockplus-firefox-*-mv2.xpi
    SOURCE_BUILD: dist/source/adblockplus-firefox-*-mv2.xpi

################################################################################
# Compliance tests
################################################################################

.compliance:
  stage: compliance
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  needs: ["build"]
  before_script:
    - apk add bash git
    - cd $[[ inputs.workspacepath ]]
  script:
    - TERMINAL=t EXTENSION=dist/release/$EXTENSION ./test/compliance.sh
  after_script:
    - cd $[[ inputs.workspacepath ]]
    - docker cp $(docker ps -aqf ancestor=compliance):/testpages.adblockplus.org/test/screenshots . 2> /dev/null
  artifacts:
    paths:
      - $[[ inputs.workspacepath ]]/screenshots/
    when: always
    expire_in: 1 month
  rules:
    - !reference [.always, rules]

.compliance:MV3:
  extends: .compliance
  variables:
    EXTENSION: adblockplus-chrome-*-mv3.zip
    MANIFEST: mv3

comp:MV3:chromium:latest:
  extends: .compliance:MV3
  variables:
    BROWSER: chromium latest

comp:MV3:edge:latest:
  extends: .compliance:MV3
  variables:
    BROWSER: edge latest

.compliance:MV2:
  extends: .compliance
  variables:
    EXTENSION: adblockplus-chrome-*-mv2.zip
    MANIFEST: mv2

comp:MV2:chromium:last-mv2-version:
  extends: .compliance:MV2
  variables:
    BROWSER: chromium 128.0.6613.0

comp:MV2:edge:latest:
  extends: .compliance:MV2
  variables:
    BROWSER: edge latest

comp:MV2:chromium:oldest:
  extends: .compliance:MV2
  variables:
    BROWSER: chromium 77.0.3865.0

comp:MV2:firefox:latest:
  extends: .compliance:MV2
  variables:
    BROWSER: firefox latest
    EXTENSION: adblockplus-firefox-*-mv2.xpi

comp:MV2:firefox:oldest:
  extends: .compliance:MV2
  variables:
    BROWSER: firefox 68.0
    EXTENSION: adblockplus-firefox-*-mv2.xpi

################################################################################
# Unit tests
################################################################################

.unit:
 extends: .build
 stage: unit
 needs: []

unit:legacy:
  extends: .unit
  script:
    - npm run -w $[[ inputs.workspacepath ]] $ test.unit.legacy

unit:standard:
  extends: .unit
  script:
    - npm run -w $[[ inputs.workspacepath ]] $ test.unit.standard

################################################################################
# UI tests
################################################################################

.uitests:
  stage: uitests
  needs: ["build"]
  before_script:
    - cd $[[ inputs.workspacepath ]]

.uitests:lambdatest:
  extends: .uitests
  variables:
    LT_USERNAME: $LT_USERNAME
    LT_ACCESS_KEY: $LT_ACCESS_KEY
    SUITE: all
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run test:$CONFIGURATION $SUITE 2>&1 | tee lambdatest_output.txt || true
    - apt-get update
    - apt-get -y install default-jre-headless
    - npx -y allure-commandline generate test/end-to-end/allure-results -o allure-report
    - |
      log_output=$(cat lambdatest_output.txt)
      regex_pattern="passed, [1-9][0-9]* failed"
      if [[ $log_output =~ $regex_pattern ]]; then
        echo "Failed test cases found. Failing the job."
        exit 1
      else
        echo "No failed test cases found. Job will pass."
      fi
  timeout: 120m
  artifacts:
    when: always
    paths:
      - $[[ inputs.workspacepath ]]/allure-report
    expire_in: 1 week
  rules:
    # Do not trigger a merge request pipeline
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $[[ inputs.parent_pipeline_source ]] == "schedule"
      when: always
    - if: $CI_COMMIT_BRANCH == "adblockplus-release"
      when: always
    - when: manual
  allow_failure: true

uitests:lambdatest:MV2:all:
  extends: .uitests:lambdatest
  variables:
    CONFIGURATION: end-to-end

uitests:lambdatest:MV2:oldbrowsers:
  extends: .uitests:lambdatest
  variables:
    CONFIGURATION: end-to-end-old-browsers
    SUITE: oldbrowsers

uitests:lambdatest:MV3:all:
  extends: .uitests:lambdatest
  before_script:
    - cd $[[ inputs.workspacepath ]]
    - npm install axios
    - export MV3_BUILD_CLOUD_URL=$(node test/end-to-end/upload-extension.js $LT_USERNAME $LT_ACCESS_KEY $CHROME_BUILD_MV3)
    - echo $MV3_BUILD_CLOUD_URL
  variables:
    CONFIGURATION: end-to-end-mv3
    CHROME_BUILD_MV3: dist/release/adblockplus-chrome-*-mv3.zip

.uitests:docker:
  extends: .uitests
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t end-to-end -f test/end-to-end/Dockerfile --build-arg MANIFEST_VERSION=$MANIFEST_VERSION --build-arg BROWSER=$BROWSER --build-arg BUILD_EXTENSION=false .
    - docker run --cpus=2 --shm-size=2g -t -e SUITE -e CI end-to-end
  after_script:
    - cd $[[ inputs.workspacepath ]]
    - IMAGE_ID=$(docker ps -aqf ancestor=end-to-end)
    - docker cp $IMAGE_ID:/adblockplus/test/end-to-end/screenshots . 2> /dev/null
  artifacts:
    paths:
      - $[[ inputs.workspacepath ]]/screenshots/
    when: on_failure
    expire_in: 1 mo
  rules:
    - !reference [.always, rules]
  variables:
    SUITE: filterlists

uitests:docker:MV2:firefox:
  extends: .uitests:docker
  variables:
    MANIFEST_VERSION: 2
    BROWSER: firefox

uitests:docker:MV2:edge:
  extends: .uitests:docker
  variables:
    MANIFEST_VERSION: 2
    BROWSER: edge

uitests:docker:MV3:chrome:
  extends: .uitests:docker
  variables:
    MANIFEST_VERSION: 3
    BROWSER: chrome
