# This file is part of AdBlock  <https://getadblock.com/>,
# Copyright (C) 2013-present Adblock, Inc.
#
# AdBlock is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# AdBlock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AdBlock.  If not, see <http://www.gnu.org/licenses/>.

spec:
  inputs:
    hostpath:
      type: string
      description: "Path to the host directory"
      default: "."

---

default:
  image: node:18.17.1
  cache:  # Cache modules using lock file
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

stages:
  - build
  - check_filesizes
  - compliance

################################################################################
# Build
################################################################################

.build:
  stage: build
  before_script:
    - cd $[[ inputs.hostpath ]]
    - npm ci --cache .npm --prefer-offline

build:
  extends: .build
  script:
    # Create extension builds
    - npx gulp build -t chrome -m 2 --unhandled-rejections=strict
    - npx gulp build -t chrome -m 3 --unhandled-rejections=strict
    - npx gulp build -t firefox -m 2 --unhandled-rejections=strict
    - npx gulp build -t chrome -m 2 --manifest_path ./build/beta_manifest.json --basename adblockbeta --unhandled-rejections=strict
    - npx gulp build -t chrome -m 3 --manifest_path ./build/beta_manifest.json --basename adblockbeta --unhandled-rejections=strict
    - npx gulp source
    # Attach commit hash to build files
    - mv adblockchrome-*-mv2.zip adblockchrome-${CI_COMMIT_SHORT_SHA}-mv2.zip
    - mv adblockchrome-*-mv3.zip adblockchrome-${CI_COMMIT_SHORT_SHA}-mv3.zip
    - mv adblockfirefox-*-mv2.xpi adblockfirefox-${CI_COMMIT_SHORT_SHA}-mv2.xpi
    - mv adblockbetachrome-*-mv2.zip adblockbetachrome-${CI_COMMIT_SHORT_SHA}-mv2.zip
    - mv adblockbetachrome-*-mv3.zip adblockbetachrome-${CI_COMMIT_SHORT_SHA}-mv3.zip
    - mv adblock-*.tar.gz adblock-${CI_COMMIT_SHORT_SHA}.tar.gz
  artifacts:
    name: "adblock-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - $[[ inputs.hostpath ]]/adblock-${CI_COMMIT_SHORT_SHA}.tar.gz
      - $[[ inputs.hostpath ]]/adblockchrome-${CI_COMMIT_SHORT_SHA}-mv2.zip
      - $[[ inputs.hostpath ]]/adblockchrome-${CI_COMMIT_SHORT_SHA}-mv3.zip
      - $[[ inputs.hostpath ]]/adblockfirefox-${CI_COMMIT_SHORT_SHA}-mv2.xpi
      - $[[ inputs.hostpath ]]/adblockbetachrome-${CI_COMMIT_SHORT_SHA}-mv2.zip
      - $[[ inputs.hostpath ]]/adblockbetachrome-${CI_COMMIT_SHORT_SHA}-mv3.zip
      - $[[ inputs.hostpath ]]/adblockfirefox-${CI_COMMIT_SHORT_SHA}-mv2.xpi

lint:
  extends: .build
  script:
    - npm run lint
    - npm run prettier
    - npm run html-hint

################################################################################
# Check filesizes
################################################################################

.check_filesizes:
  image: alpine:latest
  stage: check_filesizes
  before_script:
    - cd $[[ inputs.hostpath ]]
  script:
   - unzip -d unpacked-extension/ $EXTENSION
   - cd unpacked-extension/
   - if [ $(find . -type f -name '*.js' -size +4000k | wc -l) -gt 0 ]; then
       echo 'Some extension files are bigger than 4 MB:' &&
       find . -type f -name '*.js' -size +4000k -exec ls -lh {} \; &&
       exit 1;
     else
       echo 'All extension files are smaller than 4 MB' &&
       exit 0;
     fi

check_filesizes:chrome_mv2:
  extends: .check_filesizes
  variables:
    EXTENSION: adblockchrome-${CI_COMMIT_SHORT_SHA}-mv2.zip

check_filesizes:chrome_mv3:
  extends: .check_filesizes
  variables:
    EXTENSION: adblockchrome-${CI_COMMIT_SHORT_SHA}-mv3.zip


check_filesizes:firefox_mv2:
  extends: .check_filesizes
  variables:
    EXTENSION: adblockfirefox-${CI_COMMIT_SHORT_SHA}-mv2.xpi

################################################################################
# Ad filtering tests
################################################################################

.compliance:
  stage: compliance
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  interruptible: true
  needs: ["build"]
  before_script:
    - apk add bash git
  script:
    - TERMINAL=t ./test/compliance.sh
  after_script:
    - docker cp $(docker ps -aqf ancestor=compliance):/testpages.adblockplus.org/test/screenshots . 2> /dev/null
  artifacts:
    paths:
      - screenshots/
    when: always
    expire_in: 1 month
  rules:
    # Do not trigger merge request event pipelines
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: always

comp:MV3:chromium:latest:
  extends: .compliance
  variables:
    BROWSER: chromium latest
    EXTENSION: adblockchrome-${CI_COMMIT_SHORT_SHA}-mv3.zip

comp:MV3:edge:latest:
  extends: .compliance
  variables:
    BROWSER: edge latest
    EXTENSION: adblockchrome-${CI_COMMIT_SHORT_SHA}-mv3.zip

comp:MV2:chromium:latest:
  extends: .compliance
  variables:
    BROWSER: chromium latest
    EXTENSION: adblockchrome-${CI_COMMIT_SHORT_SHA}-mv2.zip

comp:MV2:edge:latest:
  extends: .compliance
  variables:
    BROWSER: edge latest
    EXTENSION: adblockchrome-${CI_COMMIT_SHORT_SHA}-mv2.zip

comp:MV2:firefox:latest:
  extends: .compliance
  variables:
    BROWSER: firefox latest
    EXTENSION: adblockfirefox-${CI_COMMIT_SHORT_SHA}-mv2.xpi

comp:MV2:chromium:oldest:
  extends: .compliance
  variables:
    BROWSER: chromium 77.0.3865.0
    EXTENSION: adblockchrome-${CI_COMMIT_SHORT_SHA}-mv2.zip

# https://eyeo.atlassian.net/browse/EE-542
# comp:MV2:firefox:oldest:
#   extends: .compliance
#   variables:
#     BROWSER: firefox 75.0
#     EXTENSION: adblockfirefox-${CI_COMMIT_SHORT_SHA}-mv2.xpi
