# This file is part of AdBlock  <https://getadblock.com/>,
# Copyright (C) 2013-present Adblock, Inc.
#
# AdBlock is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# AdBlock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AdBlock.  If not, see <http://www.gnu.org/licenses/>.

spec:
  inputs:
    hostpath:
      type: string
      description: "Path to the host directory"
      default: "."
    parent_pipeline_source:
      type: string
      description: "Value of CI_PIPELINE_SOURCE in the parent pipeline"

---
default:
  image: node:18.17.1
  cache: # Cache modules using lock file
    key:
      files:
        - $[[ inputs.hostpath ]]/package-lock.json
    paths:
      - $[[ inputs.hostpath ]]/.npm/
  tags:
    - "GCP"
  interruptible: true

stages:
  - build
  - check_filesizes
  - compliance

################################################################################
# Build
################################################################################

.build:
  stage: build
  before_script:
    - cd $[[ inputs.hostpath ]]
    - npm ci --cache .npm --prefer-offline

build:
  extends: .build
  script:
    # Create .env file from CI variables
    - echo "CDP_AGGREGATE_URL=\"$ADBLOCK_CDP_AGGREGATE_URL\"" >> .env
    - echo "CDP_BEARER=\"$ADBLOCK_CDP_BEARER\"" >> .env
    - echo "CDP_PING_URL=\"$ADBLOCK_CDP_PING_URL\"" >> .env
    - echo "EYEOMETRY_BEARER=\"$ADBLOCK_EYEOMETRY_BEARER\"" >> .env
    - echo "EYEOMETRY_URL=\"$ADBLOCK_EYEOMETRY_URL\"" >> .env
    # Create source archive
    - npm run build:source
    # Create MV2 extension builds
    - npm run build:release -- -t chrome -m 2 --unhandled-rejections=strict
    - npm run build:release -- -t firefox -m 2 --unhandled-rejections=strict
    # Create MV3 extension builds
    - npm run build:release -- -t chrome -m 3 --unhandled-rejections=strict
    - npm run build:release -- -t chrome -m 3 --manifest-path ./build/beta_manifest.base.json --basename adblockbeta --unhandled-rejections=strict
  artifacts:
    name: "adblock-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - $[[ inputs.hostpath ]]/dist/release/adblock-*.tar.gz
      - $[[ inputs.hostpath ]]/dist/release/adblock-chrome-*-mv2.zip
      - $[[ inputs.hostpath ]]/dist/release/adblock-chrome-*-mv3.zip
      - $[[ inputs.hostpath ]]/dist/release/adblock-firefox-*-mv2.xpi
      - $[[ inputs.hostpath ]]/dist/release/adblock-firefox-*-mv2.xpi
      - $[[ inputs.hostpath ]]/dist/release/adblockbeta-chrome-*-mv3.zip

lint:
  extends: .build
  script:
    - npm run lint
    - npm run prettier
    - npm run html-hint

################################################################################
# Check filesizes
################################################################################

.check_filesizes:
  image: alpine:latest
  stage: check_filesizes
  before_script:
    - cd $[[ inputs.hostpath ]]
  script:
    - unzip -d unpacked-extension/ dist/release/$EXTENSION
    - cd unpacked-extension/
    - if [ $(find . -type f -name '*.js' -size +4000k | wc -l) -gt 0 ]; then
      echo 'Some extension files are bigger than 4 MB:' &&
      find . -type f -name '*.js' -size +4000k -exec ls -lh {} \; &&
      exit 1;
      else
      echo 'All extension files are smaller than 4 MB' &&
      exit 0;
      fi

check_filesizes:chrome_mv2:
  extends: .check_filesizes
  variables:
    EXTENSION: adblock-chrome-*-mv2.zip

check_filesizes:chrome_mv3:
  extends: .check_filesizes
  variables:
    EXTENSION: adblock-chrome-*-mv3.zip

check_filesizes:firefox_mv2:
  extends: .check_filesizes
  variables:
    EXTENSION: adblock-firefox-*-mv2.xpi

################################################################################
# Ad filtering tests
################################################################################

.compliance:
  stage: compliance
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  needs: ["build"]
  before_script:
    - apk add bash git
    - cd $[[ inputs.hostpath ]]
  script:
    - TERMINAL=t EXTENSION=dist/release/$EXTENSION ./test/compliance.sh
  after_script:
    - cd $[[ inputs.hostpath ]]
    - docker cp $(docker ps -aqf ancestor=compliance):/testpages.adblockplus.org/test/screenshots . 2> /dev/null
  artifacts:
    paths:
      - $[[ inputs.hostpath ]]/screenshots/
    when: always
    expire_in: 1 month

comp:MV3:chromium:latest:
  extends: .compliance
  variables:
    BROWSER: chromium latest
    EXTENSION: adblock-chrome-*-mv3.zip

comp:MV3:edge:latest:
  extends: .compliance
  variables:
    BROWSER: edge latest
    EXTENSION: adblock-chrome-*-mv3.zip

comp:MV2:chromium:latest:
  extends: .compliance
  variables:
    BROWSER: chromium latest
    EXTENSION: adblock-chrome-*-mv2.zip

comp:MV2:edge:latest:
  extends: .compliance
  variables:
    BROWSER: edge latest
    EXTENSION: adblock-chrome-*-mv2.zip

comp:MV2:firefox:latest:
  extends: .compliance
  variables:
    BROWSER: firefox latest
    EXTENSION: adblock-firefox-*-mv2.xpi

comp:MV2:chromium:oldest:
  extends: .compliance
  variables:
    BROWSER: chromium 77.0.3865.0
    EXTENSION: adblock-chrome-*-mv2.zip
# https://eyeo.atlassian.net/browse/EE-542
# comp:MV2:firefox:oldest:
#   extends: .compliance
#   variables:
#     BROWSER: firefox 75.0
#     EXTENSION: adblock-firefox-*-mv2.xpi
